// This file contains a list of country codes and their corresponding names.
export const countryCodes = [
    { code: 'USA', name: 'United States' },
    { code: 'GBR', name: 'United Kingdom' },
    { code: 'TUR', name: 'Turkey' },
    { code: 'FRA', name: 'France' },
    { code: 'DEU', name: 'Germany' },
    { code: 'ITA', name: 'Italy' },
    { code: 'ESP', name: 'Spain' },
    { code: 'NLD', name: 'Netherlands' },
    { code: 'CAN', name: 'Canada' },
    { code: 'AUS', name: 'Australia' },
    { code: 'BRA', name: 'Brazil' },
    { code: 'ARG', name: 'Argentina' },
    { code: 'CHN', name: 'China' },
    { code: 'IND', name: 'India' },
    { code: 'JPN', name: 'Japan' },
    { code: 'RUS', name: 'Russia' },
    { code: 'ZAF', name: 'South Africa' },
    { code: 'MEX', name: 'Mexico' },
    { code: 'KOR', name: 'South Korea' },
    { code: 'SGP', name: 'Singapore' },
    { code: 'CHE', name: 'Switzerland' },
    { code: 'BEL', name: 'Belgium' },
    { code: 'AUT', name: 'Austria' },
    { code: 'DNK', name: 'Denmark' },
    { code: 'NOR', name: 'Norway' },
    { code: 'FIN', name: 'Finland' },
    { code: 'IRL', name: 'Ireland' },
    { code: 'PRT', name: 'Portugal' },
    { code: 'POL', name: 'Poland' },
    { code: 'CZE', name: 'Czech Republic' },
    { code: 'HUN', name: 'Hungary' },
    { code: 'ROU', name: 'Romania' },
    { code: 'SVK', name: 'Slovakia' },
    { code: 'BGR', name: 'Bulgaria' },
    { code: 'HRV', name: 'Croatia' },
    { code: 'SVN', name: 'Slovenia' },
    { code: 'LTU', name: 'Lithuania' },
    { code: 'LVA', name: 'Latvia' },
    { code: 'EST', name: 'Estonia' },
    { code: 'ISL', name: 'Iceland' },
    { code: 'CYP', name: 'Cyprus' },
    { code: 'MLT', name: 'Malta' },
    { code: 'GRC', name: 'Greece' },
    { code: 'TWN', name: 'Taiwan' },
    { code: 'THA', name: 'Thailand' },
    { code: 'PHL', name: 'Philippines' },
    { code: 'VNM', name: 'Vietnam' },
    { code: 'MYS', name: 'Malaysia' },
    { code: 'IDN', name: 'Indonesia' },
    { code: 'NZL', name: 'New Zealand' },
    { code: 'SAU', name: 'Saudi Arabia' },
    { code: 'ARE', name: 'United Arab Emirates' },
    { code: 'QAT', name: 'Qatar' },
    { code: 'KWT', name: 'Kuwait' },
    { code: 'OMN', name: 'Oman' },
    { code: 'BHR', name: 'Bahrain' },
    { code: 'EGY', name: 'Egypt' },
    { code: 'MAR', name: 'Morocco' },
    { code: 'TUN', name: 'Tunisia' },
    { code: 'DZA', name: 'Algeria' },
    { code: 'KEN', name: 'Kenya' },
    { code: 'NGA', name: 'Nigeria' },
    { code: 'ETH', name: 'Ethiopia' },
    { code: 'UGA', name: 'Uganda' },
    { code: 'TZA', name: 'Tanzania' },
    { code: 'ZMB', name: 'Zambia' },
    { code: 'ZWE', name: 'Zimbabwe' },
    { code: 'GHA', name: 'Ghana' },
    { code: 'CMR', name: 'Cameroon' },
    { code: 'CIV', name: 'Ivory Coast' },
    { code: 'PAK', name: 'Pakistan' },
    { code: 'BGD', name: 'Bangladesh' },
    { code: 'LKA', name: 'Sri Lanka' },
    { code: 'NPL', name: 'Nepal' },
    { code: 'MDV', name: 'Maldives' },
    { code: 'AFG', name: 'Afghanistan' },
    { code: 'BTN', name: 'Bhutan' },
    { code: 'MMR', name: 'Myanmar' },
    { code: 'LAO', name: 'Laos' },
    { code: 'KHM', name: 'Cambodia' },
    { code: 'BRN', name: 'Brunei' },
    { code: 'TLS', name: 'Timor-Leste' },
    { code: 'KAZ', name: 'Kazakhstan' },
    { code: 'UZB', name: 'Uzbekistan' },
    { code: 'TKM', name: 'Turkmenistan' },
    { code: 'KGZ', name: 'Kyrgyzstan' },
    { code: 'TJK', name: 'Tajikistan' },
    { code: 'ARM', name: 'Armenia' },
    { code: 'AZE', name: 'Azerbaijan' },
    { code: 'GEO', name: 'Georgia' },
    { code: 'MDA', name: 'Moldova' },
    { code: 'UKR', name: 'Ukraine' },
    { code: 'BLR', name: 'Belarus' },
    { code: 'SRB', name: 'Serbia' },
    { code: 'MNE', name: 'Montenegro' },
    { code: 'MKD', name: 'North Macedonia' },
    { code: 'ALB', name: 'Albania' },
    { code: 'BIH', name: 'Bosnia and Herzegovina' },
    { code: 'XKX', name: 'Kosovo' },
    { code: 'VAT', name: 'Vatican City' },
    { code: 'AND', name: 'Andorra' },
    { code: 'LIE', name: 'Liechtenstein' },
    { code: 'MCO', name: 'Monaco' },
    { code: 'SMR', name: 'San Marino' },
    { code: 'LUX', name: 'Luxembourg' },
    { code: 'SWE', name: 'Sweden' },
    { code: 'CUB', name: 'Cuba' },
    { code: 'DOM', name: 'Dominican Republic' },
    { code: 'JAM', name: 'Jamaica' },
    { code: 'HTI', name: 'Haiti' },
    { code: 'TTO', name: 'Trinidad and Tobago' },
    { code: 'PRY', name: 'Paraguay' },
    { code: 'URY', name: 'Uruguay' },
    { code: 'VEN', name: 'Venezuela' },
    { code: 'COL', name: 'Colombia' },
    { code: 'PER', name: 'Peru' },
    { code: 'CHL', name: 'Chile' },
    { code: 'ECU', name: 'Ecuador' },
    { code: 'BOL', name: 'Bolivia' },
    { code: 'GUY', name: 'Guyana' },
    { code: 'SUR', name: 'Suriname' }
  ];
  